version: "3.7"
services:
  database-service:
    image: postgres
    container_name: postgres-db
    environment:
      POSTGRES_DB: my-postgres-db
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: Passw0rd
    ports:
      - 5432:5432